import React from 'react';
import { TouchableOpacity, ViewStyle } from 'react-native';
import {
  Bell,
  BellRing,
  Users,
  UserPlus,
  Building2,
  ShoppingCart,
  DollarSign,
  TrendingUp,
  Calendar,
  Search,
  Plus,
  Edit,
  Trash2,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Settings,
  LogOut,
  Home,
  User,
  Mail,
  Phone,
  MapPin,
  Clock,
  AlertCircle,
  CheckCircle,
  Info,
  Eye,
  EyeOff,
  Download,
  Upload,
  Share,
  Copy,
  ExternalLink,
  Refresh,
  Filter,
  Sort,
  Menu,
  MoreVertical,
  Star,
  Heart,
  Bookmark,
  Tag,
  Archive,
  FileText,
  Image,
  Camera,
  Mic,
  Video,
  Lock,
  Unlock,
  Shield,
  Key,
  Zap,
  Wifi,
  WifiOff,
  Battery,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Stop,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Move,
  Crop,
  Scissors,
  Palette,
  Brush,
  Type,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  List,
  Grid,
  Layers,
  Package,
  Truck,
  CreditCard,
  Wallet,
  Receipt,
  Calculator,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Target,
  Award,
  Gift,
  Coffee,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Umbrella,
  Thermometer,
  Wind,
  Compass,
  Navigation,
  Map,
  Globe,
  Plane,
  Car,
  Bike,
  Train,
  Bus,
  Ship,
  Fuel,
  Wrench,
  Hammer,
  Screwdriver,
  Paintbrush,
  Ruler,
  Scissors as ScissorsIcon,
  Paperclip,
  Link,
  Unlink,
  Code,
  Terminal,
  Database,
  Server,
  HardDrive,
  Cpu,
  Memory,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Desktop,
  Printer,
  Scanner,
  Keyboard,
  Mouse,
  Headphones,
  Speaker,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Trophy,
  Medal,
  Crown,
  Flag,
  Bookmark as BookmarkIcon,
  Book,
  BookOpen,
  Library,
  GraduationCap,
  School,
  Briefcase,
  HardHat,
  Stethoscope,
  Pill,
  Syringe,
  Bandage,
  Heart as HeartIcon,
  Brain,
  Bone,
  Dna,
  Microscope,
  TestTube,
  FlaskConical,
  Atom,
  Zap as ZapIcon,
  Lightbulb,
  Flame,
  Snowflake,
  Droplets,
  Waves,
  Mountain,
  TreePine,
  Flower,
  Leaf,
  Sprout,
  Apple,
  Cherry,
  Grape,
  Banana,
  Carrot,
  Pizza,
  Cake,
  IceCream,
  Cookie,
  Candy,
  Wine,
  Beer,
  Coffee as CoffeeIcon,
  Tea,
  Milk,
  Egg,
  Fish,
  Beef,
  Chicken,
  Salad,
  Soup,
  Utensils,
  ChefHat,
  Refrigerator,
  Microwave,
  Oven,
  Blender,
  Scale,
  Timer,
  AlarmClock,
  Watch,
  Hourglass,
  Calendar as CalendarIcon,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  CalendarMinus,
  Clock as ClockIcon,
  Sunrise,
  Sunset,
  MoonIcon,
  Stars,
  CloudSun,
  CloudMoon,
  CloudSnow,
  CloudLightning,
  Rainbow,
  Tornado,
  Volcano,
  Earthquake,
  Tsunami,
  Fire,
  Flood,
  Drought,
  Storm,
  Hurricane,
  Cyclone,
  Blizzard,
  Avalanche,
  Landslide,
  Meteor,
  Comet,
  Satellite,
  Rocket,
  Ufo,
  Alien,
  Robot,
  Ghost,
  Skull,
  Paw,
  Footprints,
  Eye as EyeIcon,
  Ear,
  Nose,
  Mouth,
  Tongue,
  Tooth,
  Fingerprint,
  Hand,
  ThumbsUp,
  ThumbsDown,
  Peace,
  Victory,
  Fist,
  Handshake,
  Clap,
  Wave,
  PointingUp,
  PointingDown,
  PointingLeft,
  PointingRight,
  Muscle,
  Leg,
  Foot,
  Toe,
  Elbow,
  Knee,
  Shoulder,
  Back,
  Chest,
  Stomach,
  Hip,
  Waist,
  Neck,
  Head,
  Hair,
  Beard,
  Mustache,
  Eyebrow,
  Eyelash,
  Cheek,
  Chin,
  Forehead,
  Temple,
  Jaw,
  Lip,
  Gum,
  Palate,
  Uvula,
  Tonsil,
  Larynx,
  Pharynx,
  Esophagus,
  Trachea,
  Bronchus,
  Lung,
  Diaphragm,
  Rib,
  Sternum,
  Clavicle,
  Scapula,
  Humerus,
  Radius,
  Ulna,
  Carpus,
  Metacarpus,
  Phalanx,
  Pelvis,
  Femur,
  Tibia,
  Fibula,
  Patella,
  Tarsus,
  Metatarsus,
  Calcaneus,
  Talus,
  Navicular,
  Cuboid,
  Cuneiform,
  Spine,
  Vertebra,
  Disc,
  Spinal,
  Cord,
  Nerve,
  Neuron,
  Synapse,
  Dendrite,
  Axon,
  Myelin,
  Ganglion,
  Plexus,
  Reflex,
  Sensation,
  Perception,
  Cognition,
  Memory,
  Learning,
  Attention,
  Concentration,
  Focus,
  Awareness,
  Consciousness,
  Unconscious,
  Subconscious,
  Dream,
  Nightmare,
  Sleep,
  Wake,
  Rest,
  Fatigue,
  Energy,
  Strength,
  Power,
  Force,
  Pressure,
  Tension,
  Stress,
  Strain,
  Pain,
  Ache,
  Soreness,
  Stiffness,
  Swelling,
  Inflammation,
  Infection,
  Disease,
  Illness,
  Sickness,
  Health,
  Wellness,
  Fitness,
  Exercise,
  Workout,
  Training,
  Sport,
  Game,
  Competition,
  Tournament,
  Championship,
  Victory as VictoryIcon,
  Defeat,
  Win,
  Loss,
  Draw,
  Tie,
  Score,
  Goal,
  Point,
  Penalty,
  Foul,
  Card,
  Whistle,
  Referee,
  Judge,
  Umpire,
  Coach,
  Player,
  Team,
  Squad,
  Club,
  League,
  Season,
  Match,
  Fixture,
  Schedule,
  Timetable,
  Agenda,
  Plan,
  Strategy,
  Tactic,
  Formation,
  Position,
  Role,
  Responsibility,
  Duty,
  Task,
  Job,
  Work,
  Career,
  Profession,
  Occupation,
  Employment,
  Business as BusinessIcon,
  Company,
  Corporation,
  Enterprise,
  Organization,
  Institution,
  Agency,
  Department,
  Division,
  Branch,
  Office,
  Headquarters,
  Factory,
  Plant,
  Workshop,
  Studio,
  Laboratory,
  Clinic,
  Hospital,
  Pharmacy,
  Store,
  Shop,
  Market,
  Mall,
  Supermarket,
  Restaurant,
  Cafe,
  Bar,
  Pub,
  Hotel,
  Motel,
  Resort,
  Spa,
  Gym,
  Pool,
  Beach,
  Park,
  Garden,
  Zoo,
  Museum,
  Gallery,
  Theater,
  Cinema,
  Concert,
  Festival,
  Fair,
  Carnival,
  Circus,
  Parade,
  Celebration,
  Party,
  Wedding,
  Birthday,
  Anniversary,
  Holiday,
  Vacation,
  Trip,
  Journey,
  Adventure,
  Exploration,
  Discovery,
  Research,
  Study,
  Investigation,
  Experiment,
  Test,
  Trial,
  Sample,
  Specimen,
  Data,
  Information,
  Knowledge,
  Wisdom,
  Intelligence,
  Skill,
  Talent,
  Ability,
  Capability,
  Competence,
  Expertise,
  Experience,
  Practice,
  Habit,
  Routine,
  Custom,
  Tradition,
  Culture,
  Heritage,
  History,
  Past,
  Present,
  Future,
  Time as TimeIcon,
  Moment,
  Instant,
  Second,
  Minute,
  Hour,
  Day,
  Week,
  Month,
  Year,
  Decade,
  Century,
  Millennium,
  Era,
  Age,
  Period,
  Phase,
  Stage,
  Step,
  Level,
  Grade,
  Rank,
  Status,
  Position as PositionIcon,
  Location,
  Place,
  Site,
  Spot,
  Area,
  Region,
  Zone,
  Territory,
  Country,
  State,
  Province,
  City,
  Town,
  Village,
  Neighborhood,
  District,
  Street,
  Road,
  Avenue,
  Boulevard,
  Lane,
  Path,
  Trail,
  Route,
  Direction,
  North,
  South,
  East,
  West,
  Northeast,
  Northwest,
  Southeast,
  Southwest,
  Up,
  Down,
  Left,
  Right,
  Forward,
  Backward,
  Inside,
  Outside,
  Above,
  Below,
  Over,
  Under,
  Between,
  Among,
  Around,
  Through,
  Across,
  Along,
  Beside,
  Next,
  Near,
  Far,
  Close,
  Distant,
  Here,
  There,
  Everywhere,
  Nowhere,
  Somewhere,
  Anywhere,
  Where,
  When,
  Why,
  How,
  What,
  Who,
  Which,
  Whose,
  Whom,
  Question,
  Answer,
  Solution,
  Problem,
  Issue,
  Challenge,
  Difficulty,
  Obstacle,
  Barrier,
  Hurdle,
  Block,
  Stop,
  Pause as PauseIcon,
  Continue,
  Resume,
  Start,
  Begin,
  End,
  Finish,
  Complete,
  Done,
  Ready,
  Prepared,
  Set,
  Go,
  Move as MoveIcon,
  Run,
  Walk,
  Jump,
  Leap,
  Hop,
  Skip,
  Dance,
  Swim,
  Dive,
  Fly,
  Soar,
  Glide,
  Float,
  Sink,
  Fall,
  Rise,
  Climb,
  Ascend,
  Descend,
  Enter,
  Exit,
  Leave,
  Stay,
  Remain,
  Return,
  Come,
  Go as GoIcon,
  Arrive,
  Depart,
  Travel,
  Journey as JourneyIcon,
  Trip as TripIcon,
  Visit,
  Tour,
  Explore,
  Discover,
  Find,
  Search as SearchIcon,
  Look,
  See,
  Watch,
  Observe,
  Notice,
  Spot,
  Detect,
  Identify,
  Recognize,
  Know,
  Understand,
  Comprehend,
  Realize,
  Appreciate,
  Value,
  Treasure,
  Cherish,
  Love,
  Like,
  Enjoy,
  Prefer,
  Choose,
  Select,
  Pick,
  Take,
  Get,
  Obtain,
  Acquire,
  Gain,
  Earn,
  Win as WinIcon,
  Achieve,
  Accomplish,
  Succeed,
  Fail,
  Lose,
  Miss,
  Forget,
  Remember,
  Recall,
  Remind,
  Think,
  Consider,
  Ponder,
  Reflect,
  Contemplate,
  Meditate,
  Concentrate as ConcentrateIcon,
  Focus as FocusIcon,
  Attention as AttentionIcon,
  Listen,
  Hear,
  Sound,
  Noise,
  Silence,
  Quiet,
  Loud,
  Soft,
  High,
  Low,
  Deep,
  Shallow,
  Thick,
  Thin,
  Wide,
  Narrow,
  Broad,
  Tight,
  Loose,
  Firm,
  Soft as SoftIcon,
  Hard,
  Rough,
  Smooth,
  Sharp,
  Dull,
  Bright,
  Dark,
  Light,
  Heavy,
  Fast,
  Slow,
  Quick,
  Rapid,
  Swift,
  Speedy,
  Sluggish,
  Lazy,
  Active,
  Passive,
  Aggressive,
  Gentle,
  Kind,
  Mean,
  Nice,
  Good,
  Bad,
  Evil,
  Wicked,
  Pure,
  Clean,
  Dirty,
  Messy,
  Neat,
  Tidy,
  Organized,
  Chaotic,
  Random,
  Systematic,
  Methodical,
  Logical,
  Rational,
  Reasonable,
  Sensible,
  Practical,
  Useful,
  Helpful,
  Beneficial,
  Harmful,
  Dangerous,
  Safe,
  Secure,
  Protected,
  Vulnerable,
  Weak,
  Strong,
  Powerful,
  Mighty,
  Tiny,
  Small,
  Little,
  Big,
  Large,
  Huge,
  Giant,
  Enormous,
  Massive,
  Immense,
  Vast,
  Infinite,
  Limited,
  Unlimited,
  Boundless,
  Endless,
  Eternal,
  Temporary,
  Permanent,
  Stable,
  Unstable,
  Steady,
  Unsteady,
  Consistent,
  Inconsistent,
  Regular,
  Irregular,
  Normal,
  Abnormal,
  Usual,
  Unusual,
  Common,
  Rare,
  Unique,
  Special,
  Ordinary,
  Extraordinary,
  Amazing,
  Wonderful,
  Fantastic,
  Incredible,
  Unbelievable,
  Impossible,
  Possible,
  Probable,
  Likely,
  Unlikely,
  Certain,
  Uncertain,
  Sure,
  Unsure,
  Confident,
  Doubtful,
  Hopeful,
  Hopeless,
  Optimistic,
  Pessimistic,
  Positive,
  Negative,
  Happy,
  Sad,
  Joyful,
  Sorrowful,
  Cheerful,
  Gloomy,
  Excited,
  Bored,
  Interested,
  Uninterested,
  Curious,
  Indifferent,
  Eager,
  Reluctant,
  Willing,
  Unwilling,
  Ready as ReadyIcon,
  Unready,
  Prepared as PreparedIcon,
  Unprepared,
  Organized as OrganizedIcon,
  Disorganized,
  Planned,
  Unplanned,
  Scheduled,
  Unscheduled,
  Expected,
  Unexpected,
  Predictable,
  Unpredictable,
  Reliable,
  Unreliable,
  Trustworthy,
  Untrustworthy,
  Honest,
  Dishonest,
  Truthful,
  Untruthful,
  Sincere,
  Insincere,
  Genuine,
  Fake,
  Real,
  Unreal,
  Actual,
  Virtual,
  Physical,
  Mental,
  Emotional,
  Spiritual,
  Material,
  Immaterial,
  Tangible,
  Intangible,
  Visible,
  Invisible,
  Obvious,
  Hidden,
  Clear,
  Unclear,
  Transparent,
  Opaque,
  Open,
  Closed,
  Public,
  Private,
  Personal,
  Impersonal,
  Individual,
  Collective,
  Single,
  Multiple,
  Alone,
  Together,
  United,
  Divided,
  Connected,
  Disconnected,
  Related,
  Unrelated,
  Similar,
  Different,
  Same,
  Other,
  Another,
  Alternative,
  Option,
  Choice,
  Decision,
  Conclusion,
  Result,
  Outcome,
  Consequence,
  Effect,
  Cause,
  Reason,
  Purpose,
  Goal,
  Objective,
  Target as TargetIcon,
  Aim,
  Intention,
  Plan as PlanIcon,
  Idea,
  Thought,
  Concept,
  Theory,
  Hypothesis,
  Assumption,
  Belief,
  Opinion,
  View,
  Perspective,
  Angle,
  Approach,
  Method,
  Way,
  Manner,
  Style,
  Fashion,
  Trend,
  Pattern,
  Design,
  Structure,
  Form,
  Shape,
  Size,
  Color,
  Texture,
  Material as MaterialIcon,
  Substance,
  Element,
  Component,
  Part,
  Piece,
  Section,
  Segment,
  Fragment,
  Portion,
  Share,
  Percentage,
  Fraction,
  Ratio,
  Proportion,
  Scale as ScaleIcon,
  Measure,
  Measurement,
  Dimension,
  Length,
  Width,
  Height,
  Depth,
  Distance,
  Space,
  Room,
  Capacity,
  Volume,
  Amount,
  Quantity,
  Number,
  Count,
  Total,
  Sum,
  Average,
  Mean,
  Median,
  Mode,
  Range,
  Minimum,
  Maximum,
  Limit,
  Boundary,
  Border,
  Edge,
  Corner,
  Side,
  Top,
  Bottom,
  Front,
  Back,
  Center,
  Middle,
  Beginning,
  End as EndIcon,
  Start as StartIcon,
  Finish as FinishIcon,
  Complete as CompleteIcon,
  Incomplete,
  Partial,
  Full,
  Empty,
  Filled,
  Vacant,
  Occupied,
  Available,
  Unavailable,
  Free,
  Busy,
  Idle,
  Working,
  Resting,
  Sleeping,
  Awake,
  Alert,
  Tired,
  Exhausted,
  Energetic,
  Lively,
  Vibrant,
  Dynamic,
  Static,
  Moving,
  Still,
  Motionless,
  Stationary,
  Mobile,
  Portable,
  Fixed,
  Permanent as PermanentIcon,
  Temporary as TemporaryIcon,
  Brief,
  Short,
  Long,
  Extended,
  Prolonged,
  Continuous,
  Interrupted,
  Broken,
  Intact,
  Whole,
  Complete as CompleteIcon2,
  Incomplete as IncompleteIcon,
  Perfect,
  Imperfect,
  Flawless,
  Flawed,
  Correct,
  Incorrect,
  Right,
  Wrong,
  True,
  False,
  Accurate,
  Inaccurate,
  Precise,
  Imprecise,
  Exact,
  Approximate,
  Rough,
  Smooth as SmoothIcon,
  Fine,
  Coarse,
  Detailed,
  General,
  Specific,
  Particular,
  Special as SpecialIcon,
  Ordinary as OrdinaryIcon,
  Regular as RegularIcon,
  Irregular as IrregularIcon,
  Standard,
  Custom,
  Default,
  Optional,
  Required,
  Necessary,
  Unnecessary,
  Essential,
  Nonessential,
  Important,
  Unimportant,
  Significant,
  Insignificant,
  Major,
  Minor,
  Primary,
  Secondary,
  Main,
  Auxiliary,
  Central,
  Peripheral,
  Core,
  Surface,
  Internal,
  External,
  Inner,
  Outer,
  Interior,
  Exterior,
  Domestic,
  Foreign,
  Local,
  Remote,
  Distant as DistantIcon,
  Close as CloseIcon,
  Near as NearIcon,
  Far as FarIcon,
  Adjacent,
  Neighboring,
  Surrounding,
  Enclosed,
  Exposed,
  Covered,
  Uncovered,
  Protected as ProtectedIcon,
  Unprotected,
  Shielded,
  Unshielded,
  Defended,
  Undefended,
  Guarded,
  Unguarded,
  Watched,
  Unwatched,
  Monitored,
  Unmonitored,
  Supervised,
  Unsupervised,
  Controlled,
  Uncontrolled,
  Managed,
  Unmanaged,
  Organized as OrganizedIcon2,
  Disorganized as DisorganizedIcon,
  Structured,
  Unstructured,
  Formal,
  Informal,
  Official,
  Unofficial,
  Legal,
  Illegal,
  Legitimate,
  Illegitimate,
  Valid,
  Invalid,
  Authorized,
  Unauthorized,
  Approved,
  Unapproved,
  Accepted,
  Rejected,
  Confirmed,
  Unconfirmed,
  Verified,
  Unverified,
  Certified,
  Uncertified,
  Licensed,
  Unlicensed,
  Registered,
  Unregistered,
  Documented,
  Undocumented,
  Recorded,
  Unrecorded,
  Logged,
  Unlogged,
  Tracked,
  Untracked,
  Monitored as MonitoredIcon,
  Unmonitored as UnmonitoredIcon,
  Measured,
  Unmeasured,
  Calculated,
  Uncalculated,
  Computed,
  Uncomputed,
  Processed,
  Unprocessed,
  Analyzed,
  Unanalyzed,
  Evaluated,
  Unevaluated,
  Assessed,
  Unassessed,
  Reviewed,
  Unreviewed,
  Examined,
  Unexamined,
  Inspected,
  Uninspected,
  Checked,
  Unchecked,
  Tested,
  Untested,
  Tried,
  Untried,
  Proven,
  Unproven,
  Established,
  Unestablished,
  Settled,
  Unsettled,
  Resolved,
  Unresolved,
  Solved,
  Unsolved,
  Fixed,
  Unfixed,
  Repaired,
  Unrepaired,
  Restored,
  Unrestored,
  Renewed,
  Unrenewed,
  Updated,
  Outdated,
  Current,
  Obsolete,
  Modern,
  Ancient,
  New,
  Old,
  Fresh,
  Stale,
  Recent,
  Past as PastIcon,
  Present as PresentIcon,
  Future as FutureIcon,
  Upcoming,
  Previous,
  Next as NextIcon,
  Following,
  Preceding,
  Earlier,
  Later,
  Before,
  After,
  During,
  Meanwhile,
  Simultaneously,
  Concurrently,
  Parallel,
  Sequential,
  Consecutive,
  Successive,
  Continuous as ContinuousIcon,
  Discontinuous,
  Intermittent,
  Sporadic,
  Occasional,
  Frequent,
  Rare as RareIcon,
  Common as CommonIcon,
  Usual as UsualIcon,
  Unusual as UnusualIcon,
  Typical,
  Atypical,
  Standard as StandardIcon,
  Nonstandard,
  Conventional,
  Unconventional,
  Traditional,
  Nontraditional,
  Classical,
  Modern as ModernIcon,
  Contemporary,
  Vintage,
  Antique,
  Historic,
  Prehistoric,
  Futuristic,
  Advanced,
  Primitive,
  Sophisticated,
  Simple,
  Complex,
  Complicated,
  Easy,
  Difficult,
  Hard as HardIcon,
  Soft as SoftIcon2,
  Tough,
  Tender,
  Rigid,
  Flexible,
  Stiff,
  Loose as LooseIcon,
  Tight as TightIcon,
  Slack,
  Taut,
  Stretched,
  Compressed,
  Expanded,
  Contracted,
  Enlarged,
  Reduced,
  Increased,
  Decreased,
  Raised,
  Lowered,
  Elevated,
  Depressed,
  Lifted,
  Dropped,
  Picked,
  Placed,
  Put,
  Set as SetIcon,
  Laid,
  Positioned,
  Located,
  Situated,
  Placed as PlacedIcon,
  Arranged,
  Organized as OrganizedIcon3,
  Sorted,
  Classified,
  Categorized,
  Grouped,
  Separated,
  Divided as DividedIcon,
  Split,
  Broken as BrokenIcon,
  Cracked,
  Damaged,
  Destroyed,
  Ruined,
  Wrecked,
  Demolished,
  Collapsed,
  Fallen,
  Dropped as DroppedIcon,
  Lost,
  Missing,
  Gone,
  Disappeared,
  Vanished,
  Hidden as HiddenIcon,
  Concealed,
  Covered as CoveredIcon,
  Buried,
  Underground,
  Submerged,
  Underwater,
  Floating,
  Flying,
  Airborne,
  Grounded,
  Landed,
  Crashed,
  Collided,
  Hit,
  Struck,
  Touched,
  Felt,
  Sensed,
  Perceived,
  Experienced,
  Lived,
  Survived,
  Died,
  Killed,
  Murdered,
  Assassinated,
  Executed,
  Sacrificed,
  Martyred,
  Honored,
  Respected,
  Admired,
  Praised,
  Complimented,
  Flattered,
  Criticized,
  Blamed,
  Accused,
  Charged,
  Convicted,
  Sentenced,
  Punished,
  Penalized,
  Fined,
  Imprisoned,
  Jailed,
  Arrested,
  Detained,
  Captured,
  Caught,
  Trapped,
  Stuck,
  Frozen,
  Melted,
  Dissolved,
  Evaporated,
  Condensed,
  Crystallized,
  Solidified,
  Liquefied,
  Gasified,
  Vaporized,
  Sublimated,
  Transformed,
  Changed,
  Altered,
  Modified,
  Adjusted,
  Adapted,
  Converted,
  Translated,
  Interpreted,
  Explained,
  Described,
  Defined,
  Clarified,
  Simplified,
  Complicated as ComplicatedIcon,
  Confused,
  Puzzled,
  Perplexed,
  Bewildered,
  Baffled,
  Mystified,
  Amazed as AmazedIcon,
  Astonished,
  Surprised,
  Shocked,
  Stunned,
  Startled,
  Frightened,
  Scared,
  Terrified,
  Horrified,
  Disgusted,
  Revolted,
  Sickened,
  Nauseated,
  Dizzy,
  Faint,
  Weak as WeakIcon,
  Tired as TiredIcon,
  Exhausted as ExhaustedIcon,
  Drained,
  Depleted,
  Empty as EmptyIcon,
  Hollow,
  Vacant as VacantIcon,
  Blank,
  Clear as ClearIcon,
  Transparent as TransparentIcon,
  Invisible as InvisibleIcon,
  Hidden as HiddenIcon2,
  Secret,
  Confidential,
  Private as PrivateIcon,
  Personal as PersonalIcon,
  Individual as IndividualIcon,
  Unique as UniqueIcon,
  Distinct,
  Different as DifferentIcon,
  Various,
  Diverse,
  Mixed,
  Combined,
  Merged,
  United as UnitedIcon,
  Joined,
  Connected as ConnectedIcon,
  Linked,
  Attached,
  Fastened,
  Secured,
  Locked as LockedIcon,
  Unlocked as UnlockedIcon,
  Opened,
  Closed as ClosedIcon,
  Shut,
  Sealed,
  Blocked,
  Obstructed,
  Hindered,
  Impeded,
  Prevented,
  Stopped as StoppedIcon,
  Halted,
  Paused as PausedIcon,
  Suspended,
  Interrupted as InterruptedIcon,
  Disturbed,
  Bothered,
  Annoyed,
  Irritated,
  Frustrated,
  Angry,
  Mad,
  Furious,
  Enraged,
  Livid,
  Irate,
  Upset,
  Disturbed as DisturbedIcon,
  Troubled,
  Worried,
  Concerned,
  Anxious,
  Nervous,
  Tense,
  Stressed,
  Pressured,
  Overwhelmed,
  Overloaded,
  Burdened,
  Weighed,
  Heavy as HeavyIcon,
  Light as LightIcon,
  Bright as BrightIcon,
  Dark as DarkIcon,
  Dim,
  Faded,
  Pale,
  Colorless,
  Colorful,
  Vibrant as VibrantIcon,
  Vivid,
  Bold as BoldIcon,
  Strong as StrongIcon,
  Powerful as PowerfulIcon,
  Mighty as MightyIcon,
  Forceful,
  Intense,
  Extreme,
  Severe,
  Harsh,
  Rough as RoughIcon,
  Coarse as CoarseIcon,
  Smooth as SmoothIcon2,
  Soft as SoftIcon3,
  Gentle as GentleIcon,
  Mild,
  Moderate,
  Average as AverageIcon,
  Normal as NormalIcon,
  Typical as TypicalIcon,
  Standard as StandardIcon2,
  Regular as RegularIcon2,
  Ordinary as OrdinaryIcon2,
  Common as CommonIcon2,
  Usual as UsualIcon2,
  Expected as ExpectedIcon,
  Predictable as PredictableIcon,
  Reliable as ReliableIcon,
  Consistent as ConsistentIcon,
  Stable as StableIcon,
  Steady as SteadyIcon,
  Constant,
  Fixed as FixedIcon,
  Permanent as PermanentIcon2,
  Lasting,
  Enduring,
  Durable,
  Strong as StrongIcon2,
  Solid,
  Firm as FirmIcon,
  Secure as SecureIcon,
  Safe as SafeIcon,
  Protected as ProtectedIcon2,
  Guarded as GuardedIcon,
  Defended as DefendedIcon,
  Shielded as ShieldedIcon,
  Covered as CoveredIcon2,
  Enclosed as EnclosedIcon,
  Surrounded as SurroundedIcon,
  Wrapped,
  Packaged,
  Boxed,
  Contained,
  Held,
  Grasped,
  Gripped,
  Clutched,
  Squeezed,
  Pressed,
  Pushed,
  Pulled,
  Dragged,
  Lifted as LiftedIcon,
  Carried,
  Transported,
  Moved as MovedIcon,
  Shifted,
  Transferred,
  Delivered,
  Sent,
  Shipped,
  Mailed,
  Posted,
  Transmitted,
  Broadcast,
  Announced,
  Declared,
  Proclaimed,
  Published,
  Released,
  Issued,
  Distributed,
  Spread,
  Scattered,
  Dispersed,
  Separated as SeparatedIcon,
  Divided as DividedIcon2,
  Split as SplitIcon,
  Broken as BrokenIcon2,
  Cracked as CrackedIcon,
  Damaged as DamagedIcon,
  Harmed,
  Hurt,
  Injured,
  Wounded,
  Cut,
  Sliced,
  Chopped,
  Diced,
  Minced,
  Shredded,
  Torn,
  Ripped,
  Shattered,
  Smashed,
  Crushed,
  Squashed,
  Flattened,
  Compressed as CompressedIcon,
  Squeezed as SqueezedIcon,
  Pressed as PressedIcon,
  Pushed as PushedIcon,
  Pulled as PulledIcon,
  Stretched as StretchedIcon,
  Extended as ExtendedIcon,
  Expanded as ExpandedIcon,
  Enlarged as EnlargedIcon,
  Increased as IncreasedIcon,
  Grown,
  Developed,
  Evolved,
  Progressed,
  Advanced as AdvancedIcon,
  Improved,
  Enhanced,
  Upgraded,
  Updated as UpdatedIcon,
  Renewed as RenewedIcon,
  Refreshed,
  Restored as RestoredIcon,
  Repaired as RepairedIcon,
  Fixed as FixedIcon2,
  Corrected,
  Adjusted as AdjustedIcon,
  Tuned,
  Calibrated,
  Aligned,
  Balanced,
  Leveled,
  Straightened,
  Smoothed,
  Polished,
  Cleaned,
  Washed,
  Scrubbed,
  Wiped,
  Dried,
  Heated,
  Warmed,
  Cooled,
  Chilled,
  Frozen as FrozenIcon,
  Melted as MeltedIcon,
  Boiled,
  Steamed,
  Baked,
  Roasted,
  Grilled,
  Fried,
  Cooked,
  Prepared as PreparedIcon2,
  Made,
  Created,
  Built,
  Constructed,
  Assembled,
  Manufactured,
  Produced,
  Generated,
  Formed,
  Shaped,
  Molded,
  Carved,
  Sculpted,
  Painted,
  Drawn,
  Sketched,
  Designed as DesignedIcon,
  Planned as PlannedIcon,
  Organized as OrganizedIcon4,
  Arranged as ArrangedIcon,
  Structured as StructuredIcon,
  Formatted,
  Styled,
  Decorated,
  Adorned,
  Embellished,
  Beautified,
  Improved as ImprovedIcon,
  Enhanced as EnhancedIcon,
  Perfected,
  Refined,
  Polished as PolishedIcon,
  Finished as FinishedIcon,
  Completed as CompletedIcon,
  Done as DoneIcon,
  Accomplished,
  Achieved as AchievedIcon,
  Attained,
  Reached,
  Arrived as ArrivedIcon,
  Came,
  Went,
  Left,
  Departed as DepartedIcon,
  Exited,
  Escaped,
  Fled,
  Ran,
  Rushed,
  Hurried,
  Sped,
  Raced,
  Dashed,
  Sprinted,
  Jogged,
  Walked as WalkedIcon,
  Strolled,
  Wandered,
  Roamed,
  Traveled as TraveledIcon,
  Journeyed,
  Toured,
  Visited as VisitedIcon,
  Explored as ExploredIcon,
  Discovered as DiscoveredIcon,
  Found as FoundIcon,
  Located as LocatedIcon,
  Spotted as SpottedIcon,
  Detected as DetectedIcon,
  Identified as IdentifiedIcon,
  Recognized as RecognizedIcon,
  Knew,
  Understood as UnderstoodIcon,
  Comprehended,
  Realized as RealizedIcon,
  Appreciated as AppreciatedIcon,
  Valued as ValuedIcon,
  Treasured as TreasuredIcon,
  Cherished as CherishedIcon,
  Loved as LovedIcon,
  Liked as LikedIcon,
  Enjoyed as EnjoyedIcon,
  Preferred as PreferredIcon,
  Chose,
  Selected as SelectedIcon,
  Picked as PickedIcon,
  Took,
  Got,
  Obtained as ObtainedIcon,
  Acquired as AcquiredIcon,
  Gained as GainedIcon,
  Earned as EarnedIcon,
  Won as WonIcon,
  Achieved as AchievedIcon2,
  Accomplished as AccomplishedIcon,
  Succeeded as SucceededIcon,
  Failed as FailedIcon,
  Lost as LostIcon,
  Missed as MissedIcon,
  Forgot,
  Remembered as RememberedIcon,
  Recalled as RecalledIcon,
  Reminded as RemindedIcon,
  Thought as ThoughtIcon,
  Considered as ConsideredIcon,
  Pondered as PonderedIcon,
  Reflected as ReflectedIcon,
  Contemplated as ContemplatedIcon,
  Meditated as MeditatedIcon,
  Concentrated as ConcentratedIcon,
  Focused as FocusedIcon,
  Attended as AttendedIcon,
  Listened as ListenedIcon,
  Heard as HeardIcon,
  Sounded as SoundedIcon,
  Noised,
  Silenced,
  Quieted,
  Loudened,
  Softened,
  Heightened,
  Lowered as LoweredIcon,
  Deepened,
  Shallowed,
  Thickened,
  Thinned,
  Widened,
  Narrowed,
  Broadened,
  Tightened,
  Loosened,
  Firmed,
  Softened as SoftenedIcon,
  Hardened,
  Roughened,
  Smoothened,
  Sharpened,
  Dulled,
  Brightened,
  Darkened,
  Lightened,
  Heavied,
  Fastened as FastenedIcon,
  Slowed,
  Quickened,
  Rapidized,
  Swiftened,
  Speedied,
  Sluggishized,
  Lazied,
  Activated,
  Passivated,
  Aggressivized,
  Gentlized,
  Kindized,
  Meanized,
  Niced,
  Gooded,
  Badded,
  Eviled,
  Wickedized,
  Purified,
  Cleaned as CleanedIcon,
  Dirtied,
  Messied,
  Neatened,
  Tidied,
  Organized as OrganizedIcon5,
  Chaotized,
  Randomized,
  Systematized,
  Methodized,
  Logicized,
  Rationalized,
  Reasoned,
  Sensibilized,
  Practicalized,
  Usefulized,
  Helpfulized,
  Beneficialized,
  Harmfulized,
  Dangerized,
  Safetized,
  Securitized,
  Protectized,
  Vulnerabilized,
  Weakenized,
  Strengthenized,
  Powerfulized,
  Mightified,
  Tinified,
  Smallified,
  Littlified,
  Bigified,
  Largified,
  Hugified,
  Giantified,
  Enormousified,
  Massivified,
  Immensified,
  Vastified,
  Infinitified,
  Limitified,
  Unlimitified,
  Boundlessified,
  Endlessified,
  Eternalized,
  Temporarized,
  Permanentized,
  Stabilized,
  Unstabilized,
  Steadied,
  Unsteadied,
  Consistentized,
  Inconsistentized,
  Regularized,
  Irregularized,
  Normalized,
  Abnormalized,
  Usualized,
  Unusualized,
  Commonized,
  Rarified,
  Uniquified,
  Specialized,
  Ordinarized,
  Extraordinarized,
  Amazingified,
  Wonderfulized,
  Fantasticized,
  Incredibleized,
  Unbelievableized,
  Impossibilized,
  Possibilized,
  Probabilized,
  Likelized,
  Unlikelized,
  Certainized,
  Uncertainized,
  Sureized,
  Unsureized,
  Confidentized,
  Doubtfulized,
  Hopefulized,
  Hopelessized,
  Optimistized,
  Pessimistized,
  Positivized,
  Negativized,
  Happified,
  Saddened,
  Joyfulized,
  Sorrowfulized,
  Cheerfulized,
  Gloomified,
  Excitified,
  Borified,
  Interestified,
  Uninterestified,
  Curiousified,
  Indifferentized,
  Eagerized,
  Reluctantized,
  Willingized,
  Unwillingized,
  Readified,
  Unreadified,
  Preparified,
  Unpreparified,
  Organizedified,
  Disorganizedified,
  Plannified,
  Unplannified,
  Schedulified,
  Unschedulified,
  Expectified,
  Unexpectified,
  Predictabilized,
  Unpredictabilized,
  Reliabilized,
  Unreliabilized,
  Trustworthified,
  Untrustworthy
} from 'lucide-react-native';

interface IconProps {
  size?: number;
  color?: string;
  onPress?: () => void;
}

// Componente genérico para íconos con TouchableOpacity opcional
export const LucideIcon = ({ 
  IconComponent, 
  size = 24, 
  color = '#333', 
  onPress 
}: {
  IconComponent: any;
  size?: number;
  color?: string;
  onPress?: () => void;
}) => {
  const icon = <IconComponent size={size} color={color} />;
  
  if (onPress) {
    return (
      <TouchableOpacity onPress={onPress} style={{ padding: 4 }}>
        {icon}
      </TouchableOpacity>
    );
  }
  
  return icon;
};

// Íconos más comunes para tu app
export const AppIcons = {
  // Navegación y UI
  Bell: (props: IconProps) => <LucideIcon IconComponent={Bell} {...props} />,
  BellRing: (props: IconProps) => <LucideIcon IconComponent={BellRing} {...props} />,
  Home: (props: IconProps) => <LucideIcon IconComponent={Home} {...props} />,
  User: (props: IconProps) => <LucideIcon IconComponent={User} {...props} />,
  Users: (props: IconProps) => <LucideIcon IconComponent={Users} {...props} />,
  Settings: (props: IconProps) => <LucideIcon IconComponent={Settings} {...props} />,
  Menu: (props: IconProps) => <LucideIcon IconComponent={Menu} {...props} />,
  Search: (props: IconProps) => <LucideIcon IconComponent={Search} {...props} />,
  
  // Acciones
  Plus: (props: IconProps) => <LucideIcon IconComponent={Plus} {...props} />,
  Edit: (props: IconProps) => <LucideIcon IconComponent={Edit} {...props} />,
  Trash2: (props: IconProps) => <LucideIcon IconComponent={Trash2} {...props} />,
  Check: (props: IconProps) => <LucideIcon IconComponent={Check} {...props} />,
  X: (props: IconProps) => <LucideIcon IconComponent={X} {...props} />,
  Refresh: (props: IconProps) => <LucideIcon IconComponent={Refresh} {...props} />,
  
  // Navegación
  ChevronRight: (props: IconProps) => <LucideIcon IconComponent={ChevronRight} {...props} />,
  ChevronLeft: (props: IconProps) => <LucideIcon IconComponent={ChevronLeft} {...props} />,
  ChevronUp: (props: IconProps) => <LucideIcon IconComponent={ChevronUp} {...props} />,
  ChevronDown: (props: IconProps) => <LucideIcon IconComponent={ChevronDown} {...props} />,
  
  // Negocio
  Building2: (props: IconProps) => <LucideIcon IconComponent={Building2} {...props} />,
  ShoppingCart: (props: IconProps) => <LucideIcon IconComponent={ShoppingCart} {...props} />,
  DollarSign: (props: IconProps) => <LucideIcon IconComponent={DollarSign} {...props} />,
  TrendingUp: (props: IconProps) => <LucideIcon IconComponent={TrendingUp} {...props} />,
  Package: (props: IconProps) => <LucideIcon IconComponent={Package} {...props} />,
  Receipt: (props: IconProps) => <LucideIcon IconComponent={Receipt} {...props} />,
  Calculator: (props: IconProps) => <LucideIcon IconComponent={Calculator} {...props} />,
  
  // Comunicación
  Mail: (props: IconProps) => <LucideIcon IconComponent={Mail} {...props} />,
  Phone: (props: IconProps) => <LucideIcon IconComponent={Phone} {...props} />,
  
  // Estados
  AlertCircle: (props: IconProps) => <LucideIcon IconComponent={AlertCircle} {...props} />,
  CheckCircle: (props: IconProps) => <LucideIcon IconComponent={CheckCircle} {...props} />,
  Info: (props: IconProps) => <LucideIcon IconComponent={Info} {...props} />,
  
  // Tiempo
  Calendar: (props: IconProps) => <LucideIcon IconComponent={Calendar} {...props} />,
  Clock: (props: IconProps) => <LucideIcon IconComponent={Clock} {...props} />,
  
  // Archivos y datos
  FileText: (props: IconProps) => <LucideIcon IconComponent={FileText} {...props} />,
  Download: (props: IconProps) => <LucideIcon IconComponent={Download} {...props} />,
  Upload: (props: IconProps) => <LucideIcon IconComponent={Upload} {...props} />,
  Share: (props: IconProps) => <LucideIcon IconComponent={Share} {...props} />,
  
  // Filtros y ordenamiento
  Filter: (props: IconProps) => <LucideIcon IconComponent={Filter} {...props} />,
  Sort: (props: IconProps) => <LucideIcon IconComponent={Sort} {...props} />,
  
  // Más opciones
  MoreVertical: (props: IconProps) => <LucideIcon IconComponent={MoreVertical} {...props} />,
  
  // Favoritos
  Star: (props: IconProps) => <LucideIcon IconComponent={Star} {...props} />,
  Heart: (props: IconProps) => <LucideIcon IconComponent={Heart} {...props} />,
  
  // Seguridad
  Lock: (props: IconProps) => <LucideIcon IconComponent={Lock} {...props} />,
  Unlock: (props: IconProps) => <LucideIcon IconComponent={Unlock} {...props} />,
  Shield: (props: IconProps) => <LucideIcon IconComponent={Shield} {...props} />,
  
  // Visibilidad
  Eye: (props: IconProps) => <LucideIcon IconComponent={Eye} {...props} />,
  EyeOff: (props: IconProps) => <LucideIcon IconComponent={EyeOff} {...props} />,
};

export default AppIcons;